{% set name = "conda-recipe-manager" %}
{% set version = "0.6.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/conda-recipe-manager/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b733289c8e5d5513f4c43f90f2515d626d739cf9d0504c08ba87f24c869f2939

build:
  number: 1
  script: pip install . --no-deps --no-build-isolation -vv
  noarch: python
  entry_points:
    - conda-recipe-manager = conda_recipe_manager.commands.conda_recipe_manager:conda_recipe_manager
    - crm = conda_recipe_manager.commands.conda_recipe_manager:conda_recipe_manager

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - click >=8.1.7,<8.2.0
    - conda
    - jinja2
    - pyyaml
    - jsonschema
    - requests
    - gitpython
    - networkx
    - matplotlib-base
    - pygraphviz

test:
  imports:
    - conda_recipe_manager
  source_files:
    - .pytest.ini
    - tests/
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pytest-xdist
    - pyfakefs >=5.9.1
    - git  # Required for `gitpython` tests
  commands:
    - pip check
    - python -m pytest -n auto --ignore=tests/test_aux_files tests/

about:
  home: https://github.com/conda/conda-recipe-manager
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  license_url: https://github.com/conda/conda-recipe-manager/blob/main/LICENSE
  summary: Helper tool for recipes on aggregate.
  description: |
    Renders local recipes, provides build orders, find outdated recipes.
  doc_url: https://conda.github.io/conda-recipe-manager/index.html
  dev_url: https://github.com/conda/conda-recipe-manager

extra:
  recipe-maintainers:
    - schuylermartin45
